# Generated by Django 4.0.4 on 2022-05-08 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('zip', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=20)),
                ('size', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='AnimalLookUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.IntegerField()),
                ('animal', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='NekowitschRealtyLLC.address')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=20)),
                ('license_plate', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleLookUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.IntegerField()),
                ('vehicle', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='NekowitschRealtyLLC.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('ssn', models.IntegerField()),
                ('phone', models.IntegerField()),
                ('drivers_license', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('has_vehicle', models.BooleanField()),
                ('has_pets', models.BooleanField()),
                ('rent_per_month', models.DecimalField(
                    decimal_places=2, max_digits=6)),
                ('active', models.BooleanField(verbose_name=False)),
                ('tenancy_start_date', models.DateField()),
                ('tenancy_end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='NekowitschRealtyLLC.address')),
                ('pets', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='NekowitschRealtyLLC.animallookup')),
                ('vehicles', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='NekowitschRealtyLLC.vehiclelookup')),
            ],
        ),
    ]
