# Generated by Django 4.0.4 on 2022-05-08 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NekowitschRealtyLLC', '0005_alter_tenant_drivers_license'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='address',
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.IntegerField()),
                ('address', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='NekowitschRealtyLLC.address')),
            ],
            options={
                'ordering': ['-room_number'],
            },
        ),
        migrations.AddField(
            model_name='tenant',
            name='room',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='NekowitschRealtyLLC.rooms'),
        ),
    ]
