# Generated by Django 4.0.4 on 2022-05-08 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NekowitschRealtyLLC', '0006_remove_tenant_address_rooms_tenant_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='rent_per_month',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='tenancy_end_date',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='tenancy_start_date',
        ),
        migrations.AddField(
            model_name='rooms',
            name='rent_per_month',
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='rooms',
            name='tenancy_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='tenancy_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
