# Generated by Django 4.0.4 on 2022-05-08 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NekowitschRealtyLLC', '0007_remove_tenant_rent_per_month_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rooms',
            new_name='Room',
        ),
    ]
