# Generated by Django 4.0.4 on 2022-05-08 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0002_alter_tenant_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['-state']},
        ),
        migrations.AlterModelOptions(
            name='animal',
            options={'ordering': ['-name']},
        ),
        migrations.AlterModelOptions(
            name='animallookup',
            options={'ordering': ['-owner_id']},
        ),
        migrations.AlterModelOptions(
            name='vehicle',
            options={'ordering': ['-license_plate']},
        ),
        migrations.AlterModelOptions(
            name='vehiclelookup',
            options={'ordering': ['-owner_id']},
        ),
        migrations.AlterField(
            model_name='animallookup',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiapp.animal'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apiapp.address'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='pets',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apiapp.animallookup'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='ssn',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='tenancy_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='tenancy_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='vehicles',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apiapp.vehiclelookup'),
        ),
    ]
