# Generated by Django 4.0.4 on 2022-05-08 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0004_alter_tenant_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='drivers_license',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
